name: 🔄 Rebase beta branch on top of main

on:
  workflow_dispatch:

jobs:
  Sync:
    name: Rebase beta branch on top of main
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git rebase origin/main && git push origin beta -f
